// ===== CONFIG (SAFE FOR PUBLIC GITHUB) =====

const DAY_FRAGMENTS = 1000;
const FRAGMENTS_PER_DAY = 1000;
const SECONDS_IN_DAY = 86400;

const FRAGMENTS_PER_SECOND = FRAGMENTS_PER_DAY / SECONDS_IN_DAY;

const MINING_DURATION = 24 * 60 * 60 * 1000; // 24h
